FROM alpine:3.15

RUN echo "http://openresty.org/package/alpine/v3.15/main" >> /etc/apk/repositories \
	&& wget 'http://openresty.org/package/admin@openresty.com-5ea678a6.rsa.pub' -O /etc/apk/keys/admin@openresty.com-5ea678a6.rsa.pub \
	&& apk add --no-cache luarocks5.1 lua-inspect openresty gcc musl-dev openssl-dev lua5.1-dev lua-resty-http \
	&& luarocks-5.1 install lapis

FROM alpine:3.15

EXPOSE 8080

RUN echo "http://openresty.org/package/alpine/v3.15/main" >> /etc/apk/repositories \
    && wget 'http://openresty.org/package/admin@openresty.com-5ea678a6.rsa.pub' -O /etc/apk/keys/admin@openresty.com-5ea678a6.rsa.pub \
	&& apk add --no-cache openresty \
    && mkdir /usr/local/openresty/nginx/client_body_temp \
    && adduser -h /opt/app -D -H openresty \
    && chown -R openresty:root /usr/local/openresty/nginx/ \
    && chmod -R g=u /usr/local/openresty/nginx

COPY --from=0 /usr/share/lua/ /usr/share/lua/ 
COPY --from=0 /usr/local/lib/lua/ /usr/local/lib/lua/
COPY --from=0 /usr/local/share/lua/ /usr/local/share/lua/

COPY container/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY . /opt/app

WORKDIR /opt/app

USER 1000

CMD /usr/local/openresty/nginx/sbin/nginx -g 'daemon off; master_process on;'
