apiVersion: v1
kind: Service
metadata:
  labels:
    app: levar
  name: levar
  namespace: alert-receiver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: levar
